apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: postgres:5432
    database: crypto_db
    user: pipeline_user
    secureJsonData:
      password: pipeline_secret_2024
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: false